require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bing_articles", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BingArticle. As you add validations to BingArticle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BingArticle.create! valid_attributes
      get bing_articles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bing_article = BingArticle.create! valid_attributes
      get bing_article_url(bing_article)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bing_article_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      bing_article = BingArticle.create! valid_attributes
      get edit_bing_article_url(bing_article)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BingArticle" do
        expect {
          post bing_articles_url, params: { bing_article: valid_attributes }
        }.to change(BingArticle, :count).by(1)
      end

      it "redirects to the created bing_article" do
        post bing_articles_url, params: { bing_article: valid_attributes }
        expect(response).to redirect_to(bing_article_url(BingArticle.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BingArticle" do
        expect {
          post bing_articles_url, params: { bing_article: invalid_attributes }
        }.to change(BingArticle, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post bing_articles_url, params: { bing_article: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bing_article" do
        bing_article = BingArticle.create! valid_attributes
        patch bing_article_url(bing_article), params: { bing_article: new_attributes }
        bing_article.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bing_article" do
        bing_article = BingArticle.create! valid_attributes
        patch bing_article_url(bing_article), params: { bing_article: new_attributes }
        bing_article.reload
        expect(response).to redirect_to(bing_article_url(bing_article))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        bing_article = BingArticle.create! valid_attributes
        patch bing_article_url(bing_article), params: { bing_article: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bing_article" do
      bing_article = BingArticle.create! valid_attributes
      expect {
        delete bing_article_url(bing_article)
      }.to change(BingArticle, :count).by(-1)
    end

    it "redirects to the bing_articles list" do
      bing_article = BingArticle.create! valid_attributes
      delete bing_article_url(bing_article)
      expect(response).to redirect_to(bing_articles_url)
    end
  end
end
